import Head from "next/head";
import ActivityInput from "../../components/ActivityInput";

export default function Activity() {
  return (
    <>
      <Head>
        <title>Arto, a dog.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ActivityInput />
    </>
  );
}
